apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-avtaler-admin
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://digisos.ansatt.dev.nav.no/sosialhjelp/avtaler-admin"
  liveness:
    path: /sosialhjelp/avtaler-admin/api/internal/isAlive
  readiness:
    path: /sosialhjelp/avtaler-admin/api/internal/isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: "9137b6c8-2023-4de9-87e0-0105f01c1e5d"
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: sosialhjelp-avtaler-api-dev
