name: "Build Image and Deploy to dev"
run-name: Deploying ${{ github.ref_name }} to dev
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOCKER_IMAGE_POSTFIX: -dev

jobs:
  build-image:
    name: "Build Image for Deploy"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    outputs:
      image-tag: ${{ steps.artifact-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: "Copy appropriate env file to root"
        shell: bash
        run: |
          echo "Copying nais/envs/.env.dev..."
          cp nais/envs/.env.dev .env.production

      - name: "Build npm project"
        uses: navikt/sosialhjelp-ci/actions/build-npm@main
        with:
          node-version: 20
          build-less: "false"
          reader-token: ${{ secrets.READER_TOKEN }}
          run-test: "false"

      - name: "Upload static files to cdn"
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamdigisos
          source: ./.next/static
          destination: "/sosialhjelp-avtaler-admin/_next"
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: "Create artifact version"
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@main

      - name: "Release Tag"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.artifact-version.outputs.version }}
          commit: ${{ github.sha }}
          allowUpdates: true

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamdigisos
          tag: ${{ steps.artifact-version.outputs.version }}
          image_suffix: ${{ env.DOCKER_IMAGE_POSTFIX }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

  deploy-gcp:
    name: "Deploy to development"
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Deploy til dev"
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/dev.yaml
          CLUSTER: dev-gcp
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_IMAGE_POSTFIX }}:${{ needs.build-image.outputs.image-tag }}
