name: "Build Image and Deploy to prod"
run-name: Deploying ${{ github.ref_name }} to prod
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOCKER_IMAGE_POSTFIX: prod

jobs:
  build-image:
    name: "Build Image for Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image-tag: ${{ steps.artifact-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: "Copy appropriate env file to root"
        shell: bash
        run: |
          echo "Copying nais/envs/.env.production..."
          cp nais/envs/.env.production .env.production

      - name: "Build npm project"
        uses: navikt/sosialhjelp-ci/actions/build-npm@main
        with:
          node-version: 22
          build-less: "false"
          reader-token: ${{ secrets.READER_TOKEN }}
          run-test: "false"

      - name: "Upload static files to cdn"
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamdigisos
          source: ./.next/static
          destination: "/sosialhjelp-avtaler-admin/_next"
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdigisos
          image_suffix: ${{ env.DOCKER_IMAGE_POSTFIX }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: "Deploy til prod"
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod/prod.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          CLUSTER: prod-gcp
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
